/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Domains:

D("example.com", REGISTRAR("cloudflare"), SERVICE("cloudflare"),
    A("@", "1.2.3.4")
);

D("example.org", REGISTRAR("cloudflare"), SERVICE("cloudflare"),
    A("@", "1.2.3.4")
);

