/*
   dnsconfig.js: dnscontrol configuration generated by `dnscontrol init`.
*/

// Domains:

D("example.com", REGISTRAR("cloudflare"), SERVICE("cloudflare"),
    DefaultTTL(3600),
    A("@", "192.0.2.1"),
    A("www", "192.0.2.1"),
    MX("@", 10, "mx.example.com."),
);

